# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: mraasvel <mraasvel@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/12/12 09:51:49 by mraasvel      #+#    #+#                  #
#    Updated: 2020/12/12 10:09:54 by mraasvel      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

# compilation
CC = gcc
IFLAG = -I $(IDIR)
CFLAGS = -Wall -Werror -Wextra

# DIRS
OBJDIR = obj
SRCDIR = src
IDIR = include